### PR TITLE
Fixed the hover effect and background color  on homepage button

### PR DESCRIPTION
**Pull request by Harshsaini001**
## PR Description 📜
This PR adding the hover effect and backgroung color on homepage button.
Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes # <63>

<hr>
 
## Mark the task you have completed ✅

- [✅ ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ✅] I have performed a self-review of my own code or work.
- [ ❌] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [ ✅] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/127672737/c51ee5d3-ca40-4bac-bb66-c4e0475ee742

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by thevirengarg — CHANGES_REQUESTED** [review]
Remove unnecessary code from the index.html file which is of no use for this project and instead of <style> tag use css file for styling.

**Review by Harshsaini001 — COMMENTED** [review]
Done all the CSS part are in style tag.

**Comment by thevirengarg** [comment]
> Done all the CSS part are in style tag.

Put CSS part in CSS file not in index.html

**Comment by Harshsaini001** [comment]
I will put all CSS part in CSS file "style.css" from "index.html" file in another pull request.
So please merge both the pull request under GSSOC .

**Comment by thevirengarg** [comment]
> I will put all CSS part in CSS file "style.css" from "index.html" file in another pull request. So please merge both the pull request under GSSOC .

@Harshsaini001 I am closing this PR, you need to create a new PR with all the required changes. I will only merge one pull request.

**Pull request closed without merging**
