### PR TITLE
Enhanced Landing page buttons before and after UI experience

### PR DESCRIPTION
**Pull request by triggereddown**
## PR Description 📜
I have worked on the CSS files and edited and added the codes where the before and after indexes for the buttons were collapsing with each other and fixed that issue now the buttons doesn't have any overflow of the after effect. I have also implemented button spacing in between (as shown in the image i have attached) to enhance the UI of the website and not making it look congested.
 [Bug]: Landing page buttons needs  #107  

<hr>
 
## Mark the task you have completed ✅

- [X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

Before ->
image

After ->
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by triggereddown** [comment]
I have fixed the issue assigned to me ,just asking i didn't see any labels for Level for my task ,if possible kindly assign the label tags.
Thank you

**Review by thevirengarg — APPROVED** [review]

**Comment by thevirengarg** [comment]
@triggereddown This pull request is causing issue to the game and the content of the home page is not aligned properly. Do the changes and create a new pull request.

**Comment by triggereddown** [comment]
@thevirengarg I did not get what's the problem can you please explain it to me , because in my localhost everything's working fine and the PR here is showing merged successfully.

**Comment by thevirengarg** [comment]
@triggereddown You will be getting points for this PR, it's just that the alignment of the buttons is shifted little towards bottom, if you could correct it.

**Comment by triggereddown** [comment]
Sir it might be because i have added spacing between the buttons as there was no spacing between them previously.

**Comment by thevirengarg** [comment]
@triggereddown Create a new PR and fix it. I will score you for it as well. 

> Sir it might be because i have added spacing between the buttons as there was no spacing between them previously.

**Comment by triggereddown** [comment]
@thevirengarg can u please attach a screenshot how is this effecting the alignment  so i should be able to fix it because on my localhost it's not showing errors 
Thank you

**Pull request merged**
