### PR TITLE
Fixed Issue- #22 : Improving buttons

### PR DESCRIPTION
**Pull request by SalehaTabassum**
Hello @Durgesh4993 
Fixed issue #22
I have made the changes and added buttons .
Screenshot 2024-05-11 233047
This is before I made changes.

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/169278740/01a8fe59-568a-4819-8320-63858413c4b3

This is after I made changes.

Merge the PR and appropriate labels to it .

### CODE REVIEW

**Comment by thevirengarg** [comment]
@SalehaTabassum Mention the issue number to the PR.

**Comment by thevirengarg** [comment]
@SalehaTabassum Can you put a clear screenshot of the changes because the screen recording is very blurry.

**Comment by SalehaTabassum** [comment]
> @SalehaTabassum Can you put a clear screenshot of the changes because the screen recording is very blurry.

done added another video which is clear and mentioned the issue number in PR description

**Comment by thevirengarg** [comment]
@SalehaTabassum Make background of the buttons a little darker towards the shade of red.

**Comment by SalehaTabassum** [comment]
> @SalehaTabassum Make background of the buttons a little darker towards the shade of red.

 It's actually a gradient colour mixture of red and another colour...so you want me to make it more red?

**Comment by thevirengarg** [comment]
> > @SalehaTabassum Make background of the buttons a little darker towards the shade of red.
> 
> It's actually a gradient colour mixture of red and another colour...so you want me to make it more red?

@SalehaTabassum Actually the background of the page is dark(Red and Black) and the buttons have Red and yellowish gradient, which looking a little off.

**Review by Durgesh4993 — APPROVED** [review]
Ok

**Pull request merged**
