### PR TITLE
fixed space bugs and changed the ui, added animations, and justified …

### PR DESCRIPTION
**Pull request by manyahegde**
## PR Description 📜

Issue no. #92 

There was one spacing error, and unnecessary use of colons. I have fixed that, and also enhanced the ui.

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/107339033/78753d73-1e35-46b3-b200-c048e6f92e31

<hr>
 
## Mark the task you have completed ✅

- [x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by thevirengarg** [comment]
@manyahegde Mention the issue number, Add screenshots/screen recording in the PR description.

**Comment by manyahegde** [comment]
@thevirengarg done.

**Comment by thevirengarg** [comment]
@manyahegde merging this PR didn't made changes to the project. look into it and after it i will give you points. Overall, designing of the about page was pretty satisfying. You can create a new PR.

**Comment by manyahegde** [comment]
@thevirengarg did i get level2 points? or should i do more changes to get any points?

**Comment by thevirengarg** [comment]
@manyahegde You have got the level 2 points for this PR.

**Pull request merged**
