### PR TITLE
Added Dark theme

### LINKED ISSUE #20: [New Feature]: ADDING DARK THEME
### 🎮 feature Request

Adding dark theme to the game . pls assign this issues to me under gssoc'24 tag

### Point down the features

feature points :-  Dark theme

### Select program in which you are contributing

_No response_

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## PR Description 📜

Please include summary related to the issue you have fixed and describe your PR in brief over here by specifying the issue number on which you were working below
Fixes #20 

<hr>
 

- [x ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by thevirengarg — COMMENTED** [review]
Add screen recording of the changes to the PR description

**Comment by Saipradyumnagoud** [comment]
> Add screen recording of the changes to the PR description 

yes sure I will do it

**Comment by Saipradyumnagoud** [comment]
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/143107589/e5ad4d44-53a6-4334-86e2-d9e3b5709c2a

**Comment by Saipradyumnagoud** [comment]
Added Screen Recording

**Review by thevirengarg — CHANGES_REQUESTED** [review]
Dark mode is just changing white background to black, its not changing the theme. If instead of white background there was an image, the theme would remain same. And also the alignment of the button is not correct. There are lot of white spaces around the buttons.

**Pull request closed without merging**
