### PR TITLE
 adding a background picture that suits the website game theme

### LINKED ISSUE #54: adding a background picture that suits the website game theme
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

1)adding a background image 
2)  adding hover effects to the buttons 
This makes the page more interactive and attractive 
image

### Describe the solution you'd like

solution steps
1) adding a background image 
2) applying hover effects on the buttons

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

### PR DESCRIPTION
**Pull request by sahithinandikula**
## PR Description 📜
The PR addresses issue #54 by adding a background picture that suits the website theme and hover effects to the gameplay options 
Fixes #54 

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/138794574/c5abdf1f-86da-4326-8cdb-8ee7902ef6b1

<hr>
 
## Mark the task you have completed ✅

- [X ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] My changes generates no new warnings.
- [X ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by thevirengarg** [comment]
@sahithinandikula While making a pull request make sure to add a screen recording of changes you made to the project, or at least add a screenshot.

**Comment by sahithinandikula** [comment]
@thevirengarg I have added the screenshots and screen record of the web page

**Comment by thevirengarg** [comment]
@sahithinandikula The background image is creating a lot of unnecessary empty space, correct it. And you need to improve the overall theme of the page, I cant even give you level 1 tag for just adding an image.

**Comment by sahithinandikula** [comment]
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/138794574/0f4c46b9-8b47-4721-996a-fa03bbc6fa00

I have made the above changes , let me know if its ok to you.

**Comment by thevirengarg** [comment]
@sahithinandikula For this PR I can't even give you level 1, make more improvements or fix some more bugs.

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
you should you, redesign a custom background image. And try to make all page similar

**Comment by Durgesh4993** [comment]
image

**Comment by sahithinandikula** [comment]
okay

**Comment by sahithinandikula** [comment]
@Durgesh4993 

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/138794574/a1ba03e8-2e27-4b55-a092-d666a21b7b4d

please have a look at the changes made

**Review by thevirengarg — CHANGES_REQUESTED** [review]
The theme of the index and the game page should be same. Index being Black and red themed, you need to make sure to use the same theme for the game page. You are proposing blue and black background image, which is not matching.

**Comment by sahithinandikula** [comment]
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/138794574/649852c8-8e32-4aa9-bc43-e9f9ee339782

**Comment by thevirengarg** [comment]
@sahithinandikula This background is good. Commit the changes to the PR and I will approve it.

**Comment by sahithinandikula** [comment]
@thevirengarg sure! I have committed the changes.

**Review by thevirengarg — APPROVED** [review]

**Pull request merged**
