### PR TITLE
font style of contents change

### PR DESCRIPTION
**Pull request by vanisharma2003**
## PR Description 📜
The issue is font styling of home page contents is not as per the theme.
Fixes # <116>

 
## Mark the task you have completed ✅

- [X ] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X ] I have performed a self-review of my own code or work.
- [ X] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [X ] I have added screenshot for review.

## Add your screenshots(Optional) 📸
WhatsApp Image 2024-05-26 at 23 06 57_e3b25145
This is the screenshot of the change.

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Review by thevirengarg — CHANGES_REQUESTED** [review]
Mention the issue properly in the PR description, so the PR gets linked to the issue properly.

**Review by thevirengarg — CHANGES_REQUESTED** [review]
Also change the font of 'Physi-c-tech'.

**Comment by thevirengarg** [comment]
@vanisharma2003 resolve the conflicts.

**Comment by vanisharma2003** [comment]
> @vanisharma2003 resolve the conflicts.

Okiee

**Pull request closed without merging**
