### PR TITLE
Add a button in the About Us page to navigate back to the Home page

### LINKED ISSUE #109: Add a button in the About Us page to navigate back to the Home page
As part of the website improvements under GSSoC'24, I propose adding a button on the "About Us" page that allows users to navigate back to the Home page easily.

- Add a button styled consistently with the website's design.
- Ensure the button is responsive and works well on both desktop and mobile devices.
- Link the button to the Home page.

I would like to work on this issue. Could you please assign it to me?

### PR DESCRIPTION
**Pull request by TBorundia**
## PR Description 📜

I have added the button in about us page to navigate to home page, with CSS
 fixed #109 

<hr>
 
## Mark the task you have completed ✅

- [ ✅] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [✅ ] I have performed a self-review of my own code or work.
- [✅ ] I have commented my code, particularly in hard-to-understand areas.
- [✅ ] My changes generates no new warnings.
- [✅ ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ ✅] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸
image

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by thevirengarg** [comment]
@TBorundia Add screen recording to the PR description for review.

**Comment by TBorundia** [comment]
Uploading Button for navigation.mp4…

**Comment by TBorundia** [comment]
@thevirengarg  , Sir why this code is not merged?

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/168854094/b591026a-d57b-45dd-b8b2-bb4b90e16aef

**Comment by TBorundia** [comment]
@thevirengarg Sir why this code is not merged?

**Comment by thevirengarg** [comment]
@TBorundia Please stop spamming. You are creating unnecessary issues, for which I can't even give you level1 tag. You won't get anything by tagging me again and again. 

These are the issue:
1) Home button is never on right of the page.
2) Code had conflicts in it. 
3) The designing of the button was not matching the theme. 
4) You didn't provide the screen recording.

**Pull request closed without merging**
