### PR TITLE
Home contents style updated

### PR DESCRIPTION
**Pull request by vanisharma2003**
## PR Description 📜
Fixed issue:#116
Basically the issue is that home page contents does not have proper style as per the theme. This is not appropriate. Everything present on the website should follow a particular theme.
So for the solution I have choose a good google fonts which is appropriate as per the website.
I have made changes in CSS file.
Add links of google fonts preconnect etc in index.html.
After that I add CSS properties to respective class by inspecting the webpage.
This issue solution basically enhance the overall look of the website.

<hr>
 
## Mark the task you have completed ✅

- [ X] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ X] I have performed a self-review of my own code or work.
- [ X] I have commented my code, particularly in hard-to-understand areas.
- [ X] My changes generates no new warnings.
- [X ] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [ X] I have added screenshot for review.

<hr>

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by vanisharma2003** [comment]
WhatsApp Image 2024-05-28 at 20 45 56_efd0dea3

**Comment by thevirengarg** [comment]
@vanisharma2003 Mention the issue number properly in PR description.

**Comment by thevirengarg** [comment]
Add a screenshot or screen recording, don't click picture from another device and upload.

**Comment by vanisharma2003** [comment]
Screenshot 2024-05-29 203908

**Comment by vanisharma2003** [comment]
> Add a screenshot or screen recording, don't click picture from another device and upload.

Screenshot is added
Also I have mentioned issue number properly.
Thank you

**Review by thevirengarg — APPROVED** [review]

**Comment by thevirengarg** [comment]
@vanisharma2003 Screenshot must be added of the whole page.

**Pull request merged**
